# Generated by Django 2.2.12 on 2020-04-05 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200405_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='news_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
