# Generated by Django 2.2.12 on 2020-04-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_newsletter_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=20)),
                ('emailid', models.EmailField(max_length=254)),
                ('address', models.TextField(default=None)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('dob', models.DateField(default=None)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('pan_no', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('donation_date',),
            },
        ),
    ]
