# Generated by Django 2.2.12 on 2020-04-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donations',
            name='txnid',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='donations',
            name='txnstatus',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
