# Generated by Django 2.2.12 on 2020-04-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200406_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='orderid',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
