# Generated by Django 2.2.12 on 2020-04-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200406_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='transaction_date',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
