# Generated by Django 2.2.12 on 2020-04-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200406_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='transaction_id',
        ),
    ]
