# Generated by Django 2.2.12 on 2020-04-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_donations_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='txnstatus',
        ),
    ]
