# Generated by Django 2.2.12 on 2020-04-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_donations_txnstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('role', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='minister/%Y/%m/%d')),
                ('fblink', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('twitterlink', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('linkedinlink', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('executive', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
