# Generated by Django 2.2.12 on 2020-04-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_ministers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministers',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
