# Generated by Django 2.2.12 on 2020-04-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_ministers_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministers',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
