# Generated by Django 2.2.12 on 2020-04-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_ministers_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='sitesocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fblink', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('twitterlink', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('instalink', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('linkedlink', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ytlink', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
