# Generated by Django 2.2.12 on 2020-04-08 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_intern_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('createdate',)},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('-joindate',)},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-news_date',)},
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ('-image_date',)},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ('-video_date',)},
        ),
        migrations.AddField(
            model_name='gallery',
            name='createdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
