# Generated by Django 2.2.12 on 2020-04-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200408_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministers',
            name='rank',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
